apiVersion: v1
kind: Service
metadata:
  name: fitnessapp
spec:
  ports:
  - port: 5000  # Change this to the port your app listens on
    protocol: TCP
    targetPort: 5000  # Match this to the container port
  selector:
    app: fitnessapp
  type: LoadBalancer
